version: '3'
services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=paasdb
      - MYSQL_USER=paasdb_user
      - MYSQL_PASSWORD=secret
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      timeout: 5s
      retries: 5
    volumes:
      - database-volume:/var/lib/mysql
    networks:
      - network


  staging:
    build:
      context: ./staging
      dockerfile: Dockerfile
    volumes:
      - application-volume:/home/pkhramchenkov/App42PaaS-Java-MySQL-Sample/target/

  production:
    build:
      context: ./production
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - application-volume:/usr/local/tomcat/webapps/
    networks:
      - network

volumes:
  database-volume:
  application-volume:
networks:
  network: