#This Docker-Compose sets up 3 containers:
#databse: this container is based on base mysql 5.7 image
#stagin: this container is used to build PAAS webapp, appropriate Dockerfile is used for image
#production: this container is used to hos PAAS webapp in Tomcat9 webserver, appropriate Dockerfile is used for image
#Use URL to access PAAS app:
#http://34.68.44.187:8080/App42PaaS-Java-MySQL-Sample-0.0.1-SNAPSHOT
version: '3'
services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=paasdb_user
      - MYSQL_PASSWORD=secret
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      timeout: 5s
      retries: 5
    volumes:
      - database-volume:/var/lib/mysql
    networks:
      - network


  staging:
    build:
      context: ./staging
      dockerfile: Dockerfile
    volumes:
      - application-volume:/home/pkhramchenkov/App42PaaS-Java-MySQL-Sample/target/
      - properties-volume:/home/pkhramchenkov/App42PaaS-Java-MySQL-Sample/WebContent/

  production:
    build:
      context: ./production
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - application-volume:/usr/local/tomcat/webapps/
      - properties-volume:/usr/local/tomcat/ROOT/
    networks:
      - network

volumes:
  database-volume:
  application-volume:
  properties-volume:
networks:
  network: